# Generated by Django 2.1.10 on 2019-08-23 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo_list', '0005_wishlist_owener'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wishlist',
            old_name='owener',
            new_name='owner',
        ),
    ]
