# Generated by Django 2.2.4 on 2019-09-11 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='created_on',
        ),
        migrations.RemoveField(
            model_name='article',
            name='updated_on',
        ),
        migrations.AlterField(
            model_name='article',
            name='publish_on',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='tags',
            field=models.ManyToManyField(blank=True, default=None, null=True, to='blog.Tag'),
        ),
    ]
